import random

# Welcome Message
print("Welcome to my Number Guessing Game!\nIn this game you will begin by inputting a min and max number to determine a range.\n" \
"Then, the cpu will randomly select a number within that range.\n" \
"You will then be instructed to select a difficulty which will determine the amount of guesses available.")

# range, and secret number
min_number = int(input("Set a Minimum: "))
max_number = int(input("Set a Maximum: "))

# Random number generated by cpu
lucky_number = random.randint(min_number, max_number)

# Adding a cap to the amount of guesses the user can have
limit = 0

while limit == 0:
    difficulty = input("Please select a difficulty:\n 1. Easy(15 Guesses)\n 2. Medium(10 Guesses)\n 3. Hard(5 Guesses)\n").lower()
    if difficulty == 'easy':
        limit = 15
    elif difficulty == 'medium':
        limit = 10
    elif difficulty == 'hard':
        limit = 5
    else:
        print("Invalid difficulty. Please Try Again!")


attempts = 0

while attempts <= limit:
    guess = int(input("Guess the number: ")) # User guess

    # Game Logic
    if guess < lucky_number:
        print("Incorrect. Too low!")
        attempts += 1
    elif guess > lucky_number:
        print("Incorrect. Too High!")
        attempts += 1
    else:
        print("You Guessed the number!")
        break